spring:
  application:
    name: tracingserver
  output:
    ansi:
        enabled: DETECT

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:9411}
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"
