spring:
  application:
    name: gateway-service
  output:
    ansi:
        enabled: DETECT

server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:8080}
    preferIpAddress: true

zuul:
  routes:
    test-service:
      path: /google/**
      url: http://www.google.com
