spring:
  application:
    name: gatewayservice
  output:
    ansi:
        enabled: DETECT
  zipkin:
    base-url: http://zipkinserver:9411/

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryservice:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:8080}
    preferIpAddress: true

zuul:
  routes:
    searchengine:
      path: /searchengine/**
      url: https://www.bing.com/
    auth-service:
      path: /authservice/**
      serviceId: authservice

management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"
  endpoint:
    health:
      show-details: ALWAYS