spring:
  application:
    name: authservice
  output:
    ansi:
        enabled: DETECT
  zipkin: 
    base-url: http://localhost:9411/
  sleuth: 
    sampler: 
      probability: 1

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:8081}
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"
